Code/EXam_Info/Exam_Info/Controllers/StateController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Exam_Info.Helper;
using Exam_Info.Models;
using OfficeOpenXml;
using PagedList;

namespace Exam_Info.Controllers
{
    public class StateController : Controller
    {
        GKJ_2022Entities db = new GKJ_2022Entities();
        Common common = new Common();
        // GET: State
        public ActionResult State_Dashboard()
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model mm = common.Get_Board_Details(login_model.Index_No);
            if (login_model == null)
            {
                return RedirectToAction("Login", "Login");
            }
            return View();
        }

        public ActionResult State_Batch_List()
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model mm = common.Get_Board_Details(login_model.Index_No);
            return View();
        }
        [HttpPost]
        public ActionResult State_Batch_List(string division_name, string district_name, string taluka, string batch, string Excel)
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model mm = common.Get_Board_Details(login_model.Index_No);
            try
            {
                string Temp = "", Query = "", fileName = "";
                if (district_name != "0" && district_name != "" && district_name != null)
                {
                    Temp += " Substring(A.Index_No,1,2)='" + mm.District_Code + "'";
                }
                if (taluka != "0" && taluka != "" && taluka != null)
                {
                    Temp += " and Substring(A.Index_No,3,2)='" + taluka + "'";
                }
                if (division_name != null && division_name != "" && division_name != "0")
                {
                    Query = "select A.* from Tbl_Login A where Substring(A.Index_No,1,2) IN (select district_code from Tbl_Code_Master where division_code = " + division_name + ") and Batch = '" + batch + "'";
                }
                if (mm.Division_Code != 0 && division_name == "0" || division_name == "" || division_name == null)
                {
                    Query = "select A.* from Tbl_Login A where Substring(A.Index_No,1,2) IN (select district_code from Tbl_Code_Master where division_code = " + mm.Division_Code + ") and Batch = '" + batch + "'";
                }
                if (district_name != "0" && district_name != "" && district_name != null)
                {
                    Query = "select A.* from Tbl_Login A where" + Temp + "and Batch = '" + batch + "'";
                }

                List<Student_Model> model = db.Database.SqlQuery<Student_Model>(Query).ToList();
                if (Excel == "1")
                {
                    DataTable dt = common.ToDataTable(model);
                    dt.TableName = "Division_Batch_List";
                    fileName = DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + "Division_Batch_List";
                    common.CreateExcelFile(dt, fileName);

                }
                return Json(new { Result = true, Response = model, FileName = fileName }, JsonRequestBehavior.AllowGet);
            }

            catch (Exception ex)
            {
                return Json(new { Result = false, Response = "Unable to Fetch Record" }, JsonRequestBehavior.AllowGet);
            }

        }
        public ActionResult State_College_List()
        {
            Login_Model login_model = common.Get_Login_Details();
            List<IT_College_List_Model> tbl_College_Registrations = db.Database.SqlQuery<IT_College_List_Model>("select Index_No  from Tbl_ITCOLLEGELIST A where A.Index_No not in (select Index_No from Tbl_College_Registration)").ToList();
            return View(tbl_College_Registrations);
        }
        [HttpPost]
        public ActionResult State_College_List(string division, string district, string taluka, string Excel, string type)
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model board_Model = common.Get_Board_Details(login_model.Index_No);
            try
            {
                string Temp = "", Query = "", fileName = "";
                if (district != "0" && district != "" && district != null)
                {
                    Temp += " Substring(A.index_No,1,2)='" + district + "'";
                }
                if (taluka != "0" && taluka != "" && taluka != null)
                {
                    Temp += " and Substring(A.index_No,3,2)='" + taluka + "'";
                }
                if (type == "Complete")
                {
                    if (division != null && division != "" && division != "0")
                    {
                        Query = "select A.*, B.* from Tbl_ITCOLLEGELIST A Left join Tbl_College_Registration B on A.Index_No = B.Index_No where Substring(A.Index_No,1,2) IN (select district_code from Tbl_Code_Master where division_code = " + division + ") and B.Index_No is not null";
                    }
                    if (board_Model.Division_Code != 0 && division == null || division == "0" || division == "")
                    {
                        Query = "select A.*, B.* from Tbl_ITCOLLEGELIST A Left join Tbl_College_Registration B on A.Index_No = B.Index_No where Substring(A.Index_No,1,2) IN (select district_code from Tbl_Code_Master where division_code = " + board_Model.Division_Code + ") and B.Index_No is not null";
                    }
                    if (district != null && district != "0" && district != "")
                    {
                        Query = "select A.*, B.* from Tbl_ITCOLLEGELIST A Left join Tbl_College_Registration B on A.Index_No = B.Index_No where " + Temp + "and B.Index_No is not null";
                    }
                }

                if (type == "InComplete")
                {
                    if (division != null && division != "" && division != "0")
                    {
                        Query = "select A.*, B.* from Tbl_ITCOLLEGELIST A Left join Tbl_College_Registration B on A.Index_No = B.Index_No where Substring(A.Index_No,1,2) IN (select district_code from Tbl_Code_Master where division_code = " + division + ") and B.Index_No is null";
                    }
                    if (board_Model.Division_Code != 0 && division == null || division == "0" || division == "")
                    {
                        Query = "select A.*, B.* from Tbl_ITCOLLEGELIST A Left join Tbl_College_Registration B on A.Index_No = B.Index_No where Substring(A.Index_No,1,2) IN (select district_code from Tbl_Code_Master where division_code = " + board_Model.Division_Code + ") and B.Index_No is null";
                    }
                    if (district != null && district != "0" && district != "")
                    {
                        Query = "select A.*, B.* from Tbl_ITCOLLEGELIST A Left join Tbl_College_Registration B on A.Index_No = B.Index_No where " + Temp + "and B.Index_No is null";
                    }
                }
                List<IT_College_List_Model> model = db.Database.SqlQuery<IT_College_List_Model>(Query).ToList();
                if (Excel == "1")
                {
                    DataTable dt = common.ToDataTable(model);
                    dt.TableName = "College_Details";
                    fileName = DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + "College_Details";
                    common.CreateExcelFile(dt, fileName);

                }
                return Json(new { Result = true, Response = model, FileName = fileName }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = false, Response = "Unable to Fetch Record" + ex }, JsonRequestBehavior.AllowGet);
            }

        }
        public ActionResult State_Edit_profile()
        {
                Tbl_State_Co_Ordinator_Registration state_Dc = new Tbl_State_Co_Ordinator_Registration();

                Login_Model login_model = common.Get_Login_Details();

                int temp = db.Tbl_State_Co_Ordinator_Registration.Where(x => x.Index_No == login_model.Index_No).Count();
                if (temp > 0)
                {
                    state_Dc = db.Tbl_State_Co_Ordinator_Registration.Where(x => x.Index_No == login_model.Index_No).FirstOrDefault();
                }
                return View(state_Dc);
            
           
        }

        [HttpPost]
        public ActionResult State_Edit_profile(Tbl_State_Co_Ordinator_Registration Update_State_Info)
        {
            try
            {
                db.Tbl_State_Co_Ordinator_Registration.Add(Update_State_Info);
                if (Update_State_Info.ID != 0)
                {
                    db.Entry(Update_State_Info).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { Result = true, Response = "Record Updated Sucessfully...!" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {

            }
            return View();
        }

       

        [HttpPost]
        public JsonResult Select_District(string div)
        {
            try
            {


                var model = db.Tbl_Code_Master.Where(x => x.division_code == div).Select(n => new
                {
                    n.district_name,
                    n.district_code

                }).Distinct().OrderBy(n => n.district_name).ToList();

Code/EXam_Info/Exam_Info/Views/State/Download_Excel.cshtml
@model Exam_Info.Models.Common_Model

@{
    ViewBag.Title = "Download_Excel";
}

@if (TempData["Msg"] != null)
{
    <h4 style="color:red">@TempData["Msg"].ToString()</h4>
}

Code/EXam_Info/Exam_Info/Views/State/State_Dashboard.cshtml
@model Exam_Info.Models.Tbl_State_Co_Ordinator_Registration
@{
    ViewBag.Title = "State_Dashboard";
    Layout = "~/Views/Shared/State_LayoutPage.cshtml";
}

<div class="header" style="text-align:center">
    <h2 class="heading"><span class="mdi mdi-domain"></span>State Co-Ordinator Dashboard</h2>
</div>
<div class="container-fluid">
    <div class="row">

        <table id="statedash"></table>
    </div>
</div>

<script>

    $(document).ready(function () {
        $.ajax({
            type: 'POST',
            url: '../Admin/State_Dash_Details',
            dataType: 'json',
            data: {
            },
            beforeSend: function () {
                Showloader();
            },
            complete: function () {
                Hideloader();
            },
            success: function (data) {

                var temp = "";

                if (data.Result) {
                    $("#statedash").empty();
                    $.each(data.Response, function (i, data) {
                        debugger
                        temp += `<tr><td> <h4><a class="blink" style="color:red" href="~/Attachments/` + data.ID + `.jpg">` + (i + 1) + `) ` + data.Heading + `</a></h4></td></tr>`;
                    });
                    temp += `</tbody>`;
                    $("#statedash").append(temp);
                }
                else {
                    Error_Alert(data.Response);
                }
            },
            error: function (ex) {
                alert('Failed.' + ex);
            }
        });
    });
</script>

Code/EXam_Info/Exam_Info/Views/State/State_Data_Test3.cshtml
@model IPagedList<Exam_Info.Models.Tbl_DTT3>


@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "State_Data_Test3";
    Layout = "~/Views/Shared/State_LayoutPage.cshtml";
}

<h2>State_Data_Test3</h2>

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    #division_name {
        width: 350px;
        padding: 8px;
    }

    #taluka_name {
        width: 350px;
        padding: 8px;
    }

    #district_name {
        width: 350px;
        padding: 8px;
    }

    #btn_Excel {
        width: 200px;
        padding: 5px;
        position: absolute;
        right: 20px;
    }
</style>

@using (Html.BeginForm("State_Data_Test3", "State", FormMethod.Get))
{
    <div class="row">
        <div class="col-sm-6">
            <h2>State Data Test3</h2>
        </div>
        <div class="col-sm-6">
            <input type="button" class="btn btn-success" id="btn_Excel" value="Download Excel"><br />
        </div>
    </div>

    <div class="row" style="border:inset 2px  #3eadcf"></div>
    <br />
    <div class="table-responsive pt-3  ">
        <div class="row">
            <div class="col-sm-3">
                <label for="Division_List">Select Division</label><span style="color:Red">*</span>
                <select name="division_name" id="division_name">
                    <option value="0">--Select Division--</option>
                    <option value="1">PUNE</option>
                    <option value="2">NAGPUR</option>
                    <option value="3">AURANGABAD</option>
                    <option value="4">MUMBAI</option>
                    <option value="5">KOLHAPUR</option>
                    <option value="6">AMRAVATI</option>
                    <option value="7">NASIK</option>
                    <option value="8">LATUR</option>
                    <option value="9">KOKAN</option>
                </select>
            </div>

            <div class="col-sm-3">
                <label for="Division_List">Select District</label><span style="color:Red">*</span>

                <select name="district_name" id="district_name">
                </select>
            </div>

            <div class="col-sm-3">
                <label for="Taluka_Code">Select Taluka</label><span style="color:Red">*</span>
                <select name="taluka_name" id="taluka_name">
                </select>
            </div>
            <div class="col-sm-2">
                <label></label><br />
                <input type="submit" value="Submit" id="btn_sub" class="btn btn-success" />
            </div>
        </div>
        <br />
        <center>
            <table class="AppFormTable " id="state_insp" style="background-color: #e7fafe;">
                <tr>
                    <th>
                        Sr. No
                    </th>
                    <th>
                        Index No New
                    </th>
                    <th>
                        Index No Old
                    </th>

                    <th>
                        Date Time
                    </th>
                    <th>
                        MAC
                    </th>
                    <th>
                        Login
                    </th>
                    <th>
                        QP
                    </th>
                    <th>
                        Hit
                    </th>

                </tr>
                @{int i = 1;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <span>@i</span>
                            @{i++;}
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Index_NoN)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Index_No)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Datetime)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.MAC)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Login)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.QP)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Hit)
                        </td>
                    </tr>
                }
            </table>
        </center>

        <br />

        @Html.PagedListPager(Model, page => Url.Action("State_Data_Test2", new { page, division_name = Request.QueryString["division_name"], district_name = Request.QueryString["district_name"], taluka_name = Request.QueryString["taluka_name"] }))
    </div>
}
<script>

    $(document).ready(function () {

        $("#division_name").change(function () {
            debugger
            $("#district_name").empty();
            $.ajax({
                type: 'POST',
                url: '../State/Select_District',
                dataType: 'json',
                data: {
                    div: $("#division_name").val()
                },
                success: function (Data) {
                    for (var item in Data) {
                        $("#district_name").append('<option value="' + Data[item].Value + '">' + Data[item].Text + '</option>');
                    }

                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
            return false;
        });

        $("#district_name").change(function () {

            $("#taluka_name").empty();
            $.ajax({
                type: 'POST',
                url: '../District/Get_Taluka',
                dataType: 'json',
                data: {
                    distCode: $("#district_name").val()
                },
                success: function (Data) {
                    for (var item in Data) {
                        $("#taluka_name").append('<option value="' + Data[item].Value + '">' + Data[item].Text + '</option>');
                    }
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
            return false;
        });

        $("#btn_sub").click(function () {

            Get_Inspection_Record("0");

        });
        $("#btn_Excel").click(function () {

            Get_Inspection_Record("1");

        });


        //var list2 = JSON.parse(JSON.stringify(data.Response));
        //for (i in list2) {
        //    var daate = list2[i].Datetime;
        //    function jsondate_to_normaldate(daate) {
        //        var dateString = daate.substr(6);
        //        var currentTime = new Date(parseInt(dateString));
        //        var month = currentTime.getMonth() + 1;
        //        var day = currentTime.getDate();
        //        var year = currentTime.getFullYear();

        //        var hour = currentTime.getHours();
        //        var min = currentTime.getMinutes();

        //        var date = day + "-" + month + "-" + year + " " + hour + ":" + min + " ";
        //        return date;
        //    }
        //}

        function Get_Inspection_Record(Excel) {
            debugger
            $.ajax({
                type: 'POST',
                url: '../State/State_Data_Test3',
                dataType: 'json',
                data: {
                    division_name: $("#division_name").val(),
                    district: $("#district_name").val(),
                    taluka: $("#taluka_name").val(),
                    Excel: Excel
                },
                beforeSend: function () {
                    Showloader();
                },
                complete: function () {
                    Hideloader();
                },
                success: function (data) {

                    if (data.Result) {
                        $("#state_insp").empty();

                        //var list2 = JSON.parse(JSON.stringify(data.Response));
                        //for (i in list2) {
                        //    delete list2[i].ID;


                        //    var aa = list2[i].Datetime;
                        //    var JavaScriptDate = new Date(parseInt(aa.substr(6)));
                        //    var dateObject = new Date(JavaScriptDate);
                        //    var daate = dateObject.getDate();
                        //    var Month = dateObject.getMonth() + 1;
                        //    var year = dateObject.getFullYear();
                        //    list2[i].Date_Time = daate + "/" + Month + "/" + year;
                        //}
                        //Bind_Table(list2, "state_insp");
                        if (Excel == "1") {
                            window.location.href = "../Excel_files/" + data.FileName + ".xlsx";
                        }
                    }
                    else {
                        Error_Alert(data.Message);
                    }
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        }
    });


</script>

Code/EXam_Info/Exam_Info/Views/State/State_List.cshtml
@model IEnumerable<Exam_Info.Models.Student_Model>
@{
    ViewBag.Title = "State_List";
    Layout = "~/Views/Shared/State_LayoutPage.cshtml";
}





<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    #division_name {
        width: 350px;
        padding: 8px;
    }

    #taluka_name {
        width: 350px;
        padding: 8px;
    }

    #district_name {
        width: 350px;
        padding: 8px;
    }

    #btn_Excel {
        width: 200px;
        padding: 5px;
        position: absolute;
        right: 20px;
    }
</style>

@using (Html.BeginForm("State_List", "State", FormMethod.Get))
{
    <div class="row">
        <div class="col-sm-6">
            <h2>State List</h2>
        </div>
        <div class="col-sm-6">
            <input type="button" class="btn btn-success" id="btn_Excel" value="Download Excel"><br />
        </div>
    </div>

    <div class="row" style="border:inset 2px  #3eadcf"></div>
    <br />
    <div class="table-responsive pt-3  ">
        <div class="row">
            <div class="col-sm-3">
                <label for="Division_List">Select Division</label><span style="color:Red">*</span>
                <select name="division_name" id="division_name">
                    <option value="0">--Select Division--</option>
                    <option value="1">PUNE</option>
                    <option value="2">NAGPUR</option>
                    <option value="3">AURANGABAD</option>
                    <option value="4">MUMBAI</option>
                    <option value="5">KOLHAPUR</option>
                    <option value="6">AMRAVATI</option>
                    <option value="7">NASIK</option>
                    <option value="8">LATUR</option>
                    <option value="9">KOKAN</option>
                </select>
            </div>

            <div class="col-sm-3">
                <label for="Division_List">Select District</label><span style="color:Red">*</span>

                <select name="district_name" id="district_name">
                </select>
            </div>

            <div class="col-sm-3">
                <label for="Taluka_Code">Select Taluka</label><span style="color:Red">*</span>
                <select name="taluka_name" id="taluka_name">
                </select>
            </div>
            <div class="col-sm-2">
                <label></label><br />
                <input type="submit" value="Submit" id="btn_sub" class="btn btn-success" />
            </div>
        </div>
        <br />
        @if (Model != null)
        {
            <center>
                <table class="AppFormTable " id="state_insp" style="background-color: #e7fafe;">
                    <thead>
                        <tr>
                            <th>
                                Sr.No.
                            </th>
                            <th>
                                Index No
                            </th>
                            <th>
                                Seat No
                            </th>
                            <th>
                                Name
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{int i = 1;}
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <span>@i</span>
                                    @{i++;}

                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.Index_No)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.Seat_No)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.Name)
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            </center>


        }

        <br />
    </div>

    <br />
  }

    <script>

        $(document).ready(function () {

            $("#division_name").change(function () {

                $("#district_name").empty();
                $.ajax({
                    type: 'POST',
                    url: '../State/Select_District',
                    dataType: 'json',
                    data: {
                        div: $("#division_name").val()
                    },
                    success: function (Data) {
                        for (var item in Data) {
                            $("#district_name").append('<option value="' + Data[item].Value + '">' + Data[item].Text + '</option>');
                        }

                    },
                    error: function (ex) {
                        alert('Failed.' + ex);
                    }
                });
                return false;
            });

            $("#district_name").change(function () {

                $("#taluka_name").empty();
                $.ajax({
                    type: 'POST',
                    url: '../District/Get_Taluka',
                    dataType: 'json',
                    data: {
                        distCode: $("#district_name").val()
                    },
                    success: function (Data) {
                        for (var item in Data) {
                            $("#taluka_name").append('<option value="' + Data[item].Value + '">' + Data[item].Text + '</option>');
                        }
                    },
                    error: function (ex) {
                        alert('Failed.' + ex);
                    }
                });
                return false;
            });


            $("#btn_sub").click(function () {

                Get_Inspection_Record("0");

            });
            $("#btn_Excel").click(function () {

                Get_Inspection_Record("1");

            });



        });



        function Get_Inspection_Record(Excel) {
            debugger
            $.ajax({
                type: 'POST',
                url: '../State/State_List',
                dataType: 'json',
                data: {
                    division_name: $("#division_name").val(),
                    dist: $("#district_name").val(),
                    taluka: $("#taluka_name").val(),
                    Excel: Excel
                },
                beforeSend: function () {
                    Showloader();
                },
                complete: function () {
                    Hideloader();
                },
                success: function (data) {

                    if (data.Result) {
                        $("#state_insp").empty();

                        //var list2 = JSON.parse(JSON.stringify(data.Response));
                        //for (i in list2) {
                        //    delete list2[i].ID;
                        //    delete list2[i].Active;


                        //    var aa = list2[i].Date_Time;
                        //    var JavaScriptDate = new Date(parseInt(aa.substr(6)));
                        //    var dateObject = new Date(JavaScriptDate);
                        //    var daate = dateObject.getDate();
                        //    var Month = dateObject.getMonth() + 1;
                        //    var year = dateObject.getFullYear();
                        //    list2[i].Date_Time = daate + "/" + Month + "/" + year;



                        //}


                        /* Bind_Table(list2, "state_insp");*/
                        if (Excel == "1") {

                            window.location.href = "../Excel_Files/" + data.FileName + ".xlsx";

                        }
                    }
                    else {
                        Error_Alert(data.Message);
                    }
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        }


    </script>