Code/EXam_Info/Exam_Info/Controllers/DivisionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exam_Info.Helper;
using Exam_Info.Models;
using PagedList;
using PagedList.Mvc;

namespace Exam_Info.Controllers
{
    public class DivisionController : Controller
    {
        GKJ_2022Entities db = new GKJ_2022Entities();
        Common common = new Common();

        // GET: Division
        public ActionResult Division_Dashboard()
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model mm = common.Get_Board_Details(login_model.Index_No);
            if (login_model == null)
            {
                return RedirectToAction("Login", "Login");
            }
            return View();
        }
        public ActionResult Division_Batch_List()
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model mm = common.Get_Board_Details(login_model.Index_No);
            TempData["Division_Code"] = mm.Division_Code;
            return View();
        }
        [HttpPost]
        public ActionResult Division_Batch_List(string dist, string taluka, string batch, string Excel)
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model mm = common.Get_Board_Details(login_model.Index_No);
            try
            {
                string Temp = "", Query = "", fileName = "";
                if (dist != "0" && dist != "" && dist != null)
                {
                    Temp += " Substring(A.Index_No,1,2)='" + mm.District_Code + "'";
                }
                if (taluka != "0" && taluka != "" && taluka != null)
                {
                    Temp += " and Substring(A.Index_No,3,2)='" + taluka + "'";
                }
                if (mm.Division_Code != 0 && dist == "0" || dist == "" || dist == null)
                {
                    Query = "select A.* from Tbl_Login A where Substring(A.Index_No,1,2) IN (select district_code from Tbl_Code_Master where division_code = " + mm.Division_Code + ") and Batch = '" + batch + "'";
                }
                else
                {
                    Query = "select A.* from Tbl_Login A where" + Temp + "and Batch = '" + batch + "'";
                }

                List<Student_Model> model = db.Database.SqlQuery<Student_Model>(Query).ToList();
                if (Excel == "1")
                {
                    DataTable dt = common.ToDataTable(model);
                    dt.TableName = "Division_Batch_List";
                    fileName = DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + "Division_Batch_List";
                    common.CreateExcelFile(dt, fileName);

                }
                return Json(new { Result = true, Response = model, FileName = fileName }, JsonRequestBehavior.AllowGet);
            }

            catch (Exception ex)
            {
                return Json(new { Result = false, Response = "Unable to Fetch Record" }, JsonRequestBehavior.AllowGet);
            }

        }
        public ActionResult Division_College_List()
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model mm = common.Get_Board_Details(login_model.Index_No);
            TempData["Division_Code"] = mm.Division_Code;
            return View();
        }
        [HttpPost]
        public ActionResult Division_College_List(string district, string taluka, string Excel, string type)
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model board_Model = common.Get_Board_Details(login_model.Index_No);
            try
            {
                string Temp = "", Query = "", fileName = "";
                if (district != "0" && district != "" && district != null)
                {
                    Temp += " Substring(A.index_No,1,2)='" + district + "'";
                }
                if (taluka != "0" && taluka != "" && taluka != null)
                {
                    Temp += " and Substring(A.index_No,3,2)='" + taluka + "'";
                }
                if (type == "Complete")
                {
                    if (board_Model.Division_Code != 0 && district == null || district == "0" || district == "")
                    {
                        Query = "select A.*, B.* from Tbl_ITCOLLEGELIST A Left join Tbl_College_Registration B on A.Index_No = B.Index_No where Substring(A.Index_No,1,2) IN (select district_code from Tbl_Code_Master where division_code = " + board_Model.Division_Code + ") and B.Index_No is not null";
                    }
                    if (district != null && district != "0" && district != "")
                    {
                        Query = "select A.*, B.* from Tbl_ITCOLLEGELIST A Left join Tbl_College_Registration B on A.Index_No = B.Index_No where " + Temp + "and B.Index_No is not null";
                    }
                }

                if (type == "InComplete")
                {
                    if (board_Model.Division_Code != 0)
                    {
                        Query = "select A.*, B.* from Tbl_ITCOLLEGELIST A Left join Tbl_College_Registration B on A.Index_No = B.Index_No where Substring(A.Index_No,1,2) IN (select district_code from Tbl_Code_Master where division_code = " + board_Model.Division_Code + ") and B.Index_No is null";
                    }
                    if (district != null && district != "0" && district != "")
                    {
                        Query = "select A.*, B.* from Tbl_ITCOLLEGELIST A Left join Tbl_College_Registration B on A.Index_No = B.Index_No where " + Temp + "and B.Index_No is null";
                    }
                }
                List<IT_College_List_Model> model = db.Database.SqlQuery<IT_College_List_Model>(Query).ToList();
                if (Excel == "1")
                {
                    DataTable dt = common.ToDataTable(model);
                    dt.TableName = "College_Details";
                    fileName = DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + "College_Details";
                    common.CreateExcelFile(dt, fileName);

                }
                return Json(new { Result = true, Response = model, FileName = fileName }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = false, Response = "Unable to Fetch Record" + ex }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpPost]
        public JsonResult Load_Taluka(string distCode)
        {
            List<SelectListItem> list = common.Get_Taluka_List(distCode);

            return Json(new SelectList(list, "Value", "Text", JsonRequestBehavior.AllowGet));
        }
        public JsonResult Get_District(string divCode)
        {
            List<SelectListItem> list = common.Get_District_List(divCode);

            return Json(new SelectList(list, "Value", "Text", JsonRequestBehavior.AllowGet));
        }
        public ActionResult Division_Edit_profile()
        {
            Tbl_Division_Co_Ordinator_Registration dc = new Tbl_Division_Co_Ordinator_Registration();
            //string Index = Session["Index_No"].ToString();
            Login_Model login_model = common.Get_Login_Details();

            int temp = db.Tbl_Division_Co_Ordinator_Registration.Where(x => x.Index_No == login_model.Index_No).Count();
            if (temp > 0)
            {
                dc = db.Tbl_Division_Co_Ordinator_Registration.Where(x => x.Index_No == login_model.Index_No).FirstOrDefault();
            }
            return View(dc);
        }

        [HttpPost]
        public ActionResult Division_Edit_profile(Tbl_Division_Co_Ordinator_Registration Update_Division_Info)
        {
            try
            {
                db.Tbl_Division_Co_Ordinator_Registration.Add(Update_Division_Info);
                if (Update_Division_Info.ID != 0)
                {
                    db.Entry(Update_Division_Info).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { Result = true, Response = "Record Updated Sucessfully...!" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {

            }
            return View();
        }

        public ActionResult Division_Inspection()
        {
            //var div = Session["Division_Code"].ToString();
            Login_Model login_model = common.Get_Login_Details();
            Board_Model mm = common.Get_Board_Details(login_model.Index_No);

            var model = db.Tbl_Code_Master.Where(x => x.division_code == mm.Division_Code.ToString()).Select(n => new
            {
                n.district_name,
                n.district_code

            }).Distinct().OrderBy(n => n.district_name).ToList();

            List<SelectListItem> list = new List<SelectListItem>();
            list.Add(new SelectListItem { Text = "--Select District--", Value = "0" });
            if (model != null)
            {
                foreach (var item in model)
                {
                    list.Add(new SelectListItem { Text = item.district_name.ToString(), Value = item.district_code.ToString() });
                }
            }
            ViewBag.DistrictList = new SelectList(list, "Value", "Text");
            return View();
        }


        //public JsonResult Division_Inspection(string district, string taluka)
        //{
        //    var model = db.Tbl_Inspection.Where(x => x.Index_No.Substring(0, 2) == district && x.Index_No.Substring(2, 2) == taluka).AsEnumerable().Select((n, i) => new
        //    {

Code/EXam_Info/Exam_Info/Views/Division/Divi_Stud_Login.cshtml
@using PagedList;
@using PagedList.Mvc;

@*@model Exam_Info.Models.Tbl_Code_Master*@

@model IPagedList<Exam_Info.Models.Student_Model>
@{
    ViewBag.Title = "Divi_Stud_Login";
    Layout = "~/Views/Shared/Division_LayoutPage.cshtml";
}

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    #dist {
        width: 526px;
        padding: 8px;
    }

    #taluka {
        width: 526px;
        padding: 8px;
    }

    #btn_Excel {
        width: 200px;
        padding: 5px;
        position: absolute;
        right: 20px;
    }
</style>

<div class="row">
    <div class="col-sm-6">
        <h2>Division Student List</h2>
    </div>
    <div class="col-sm-6">
        <input type="button" class="btn btn-success" id="btn_Excel" value="Download Excel"><br />
    </div>
</div>

<div class="row" style="border:inset 2px  #3eadcf"></div>
<br />
@using (Html.BeginForm("Divi_Stud_Login", "Division", FormMethod.Get))
{
    <div>
        @Html.Hidden("Div_Code", @TempData["Division_Code"])
        <div class="row">

            <div class="col-sm-4">
                <label for="Division_List">Select District</label><span style="color:Red">*</span>
                <select name="dist" id="dist">
                </select>
            </div>

            <div class="col-sm-4">
                <label for="Taluka_Code">Select Taluka</label><span style="color:Red">*</span>
                <select name="taluka" id="taluka">
                </select>
            </div>
            <div class="col-sm-1">
                <center>
                    <label></label><br />
                    <input type="submit" value="Submit" id="btn_sub" class="btn btn-success" />
                </center>
            </div>
        </div>

        <br />
        @if (Model != null)
        {
            <center>
                <table class="AppFormTable " id="state_insp" style="background-color: #e7fafe;">
                    <thead>
                        <tr>
                            <th>
                                Sr.No.
                            </th>
                            <th>
                                Index No
                            </th>
                            <th>
                                Seat No
                            </th>
                            <th>
                                Name
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{int i = 1;}
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <span>@i</span>
                                    @{i++;}

                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.Index_No)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.Seat_No)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.Name)
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>
            </center>
        }
        <br />
    </div>
    @Html.PagedListPager(Model, page => Url.Action("Divi_Stud_Login", new { page, dist = Request.QueryString["dist"], taluka = Request.QueryString["taluka"] }))


}



<script>

    $(document).ready(function () {

        $("#taluka").empty();
        $("#dist").empty();

        $.ajax({
            type: 'POST',
            url: '../Division/Get_District',
            dataType: 'json',
            data: {
                divCode: $("#Div_Code").val()
            },
            success: function (Data) {
                for (var item in Data) {
                    $("#dist").append('<option value="' + Data[item].Value + '">' + Data[item].Text + '</option>');
                }

            },
            error: function (ex) {
                alert('Failed.' + ex);
            }
        });

        $("#dist").change(function () {

            $.ajax({
                type: 'POST',
                url: '../Division/Load_Taluka',
                dataType: 'json',
                data: {
                    distCode: $("#dist").val()
                },
                success: function (Data) {
                    $("#taluka").empty();
                    for (var item in Data) {
                        $("#taluka").append('<option value="' + Data[item].Value + '">' + Data[item].Text + '</option>');
                    }

                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        });


        $("#btn_Excel").click(function () {

            Get_Inspection_Record("1");

        });


        function Get_Inspection_Record(Excel) {

            $.ajax({
                type: 'POST',
                url: '../Division/Division_List',
                dataType: 'json',
                data: {
                    dist: $("#dist").val(),
                    taluka: $("#taluka").val(),
                    Excel: Excel
                },
                beforeSend: function () {
                    Showloader();
                },
                complete: function () {
                    Hideloader();
                },
                success: function (data) {

                    if (data.Result) {

                        if (Excel == "1") {

                            window.location.href = "../State/" + data.FileName + ".xlsx";

                        }
                    }
                    else {
                        Error_Alert(data.Response);
                    }
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        }


    });
</script>
@*@Html.PagedListPager(Model, page => Url.Action("Divi_Stud_Login", new { page }))*@

Code/EXam_Info/Exam_Info/Views/Division/Division_Batch_List.cshtml
@model Exam_Info.Models.Student_Model
@{
    ViewBag.Title = "Division_Batch_List";
    Layout = "~/Views/Shared/Division_LayoutPage.cshtml";
}




<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    #dist {
        width: 526px;
        padding: 8px;
    }

    #taluka {
        width: 526px;
        padding: 8px;
    }

    #btn_Excel {
        width: 200px;
        padding: 5px;
        position: absolute;
        right: 20px;
    }
</style>


<div class="row">
    <div class="col-sm-6">
        <h2>Student Batch List</h2>
    </div>
    <div class="col-sm-6">
        <input type="button" class="btn btn-success" id="btn_Excel" value="Download Excel"><br />
    </div>
</div>
<br />
<div class="row" style="border:inset 2px  #3eadcf"></div>
<br />
<form id="batch_form">
    <div class="row">
        @Html.Hidden("Div_Code", @TempData["Division_Code"])
        <div class="col-sm-4">
            <label for="Division_List">Select District</label><span style="color:Red">*</span>
            <select name="dist" id="dist">
            </select>
        </div>

        <div class="col-sm-4">
            <label for="Taluka_Code">Select Taluka</label><span style="color:Red">*</span>
            <select name="taluka" id="taluka">
            </select>
        </div>
        <div class="col-sm-2">
            <label>Select Batch :</label>
            @Html.DropDownListFor(m => m.Batch, new List<SelectListItem> {
            new SelectListItem { Text = "Select Batch",   Value = "0", Selected = true,Disabled = true},
            new SelectListItem{Text="B1", Value="B1"},
            new SelectListItem{Text="B2", Value="B2"},
            new SelectListItem{Text="B3", Value="B3"},
            new SelectListItem{Text="B4", Value="B4"},
            new SelectListItem{Text="B5", Value="B5"},
            new SelectListItem{Text="B6", Value="B6"},
            }, new { @name = "Type", @class = "form-control" })
        </div>
        <div class="col-sm-2">
            <label></label><br />
            <input type="button" class="btn btn-success" id="btn_submit" value="Submit"><br />
        </div>
    </div>
    <br />
    <br />
    <center>
        <table class="AppFormTable" id="tbl_batch" style="background-color: #e7fafe;"></table>
    </center>
</form>
<script>
    $(document).ready(function () {

        $("#taluka").empty();
        $("#dist").empty();

        $.ajax({
            type: 'POST',
            url: '../Division/Get_District',
            dataType: 'json',
            data: {
                divCode: $("#Div_Code").val()
            },
            success: function (Data) {
                for (var item in Data) {
                    $("#dist").append('<option value="' + Data[item].Value + '">' + Data[item].Text + '</option>');
                }

            },
            error: function (ex) {
                alert('Failed.' + ex);
            }
        });

        $("#dist").change(function () {
            debugger
            $.ajax({
                type: 'POST',
                url: '../Division/Load_Taluka',
                dataType: 'json',
                data: {
                    distCode: $("#dist").val()
                },
                success: function (Data) {
                    $("#taluka").empty();
                    for (var item in Data) {
                        $("#taluka").append('<option value="' + Data[item].Value + '">' + Data[item].Text + '</option>');
                    }

                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        });


        $("#btn_submit").click(function () {

            Get_Inspection_Record("0");

        });

        $("#btn_Excel").click(function () {

            Get_Inspection_Record("1");

        });


        function Get_Inspection_Record(Excel) {
            $.ajax({
                type: 'POST',
                url: '../Division/Division_Batch_List',
                dataType: 'json',
                data: {
                    dist: $("#dist").val(),
                    taluka: $("#taluka").val(),
                    batch: $("#Batch").val(),
                    Excel: Excel
                },
                beforeSend: function () {
                    Showloader();
                },
                complete: function () {
                    Hideloader();
                },
                success: function (data) {

                    var temp = "";
                    temp += `<thead><tr><td>Sr.No.</td><td>Seat No</td><td>Name</td></tr></thead><tbody`;
                    if (data.Result) {
                        $("#tbl_batch").empty();
                        $.each(data.Response, function (i, data) {
                            temp += `<tr><td>` + (i + 1) + `</td><td>` + data.Seat_No + `</td><td>` + data.Name + `</td></tr>`;
                        });
                        temp += `</tbody>`;
                        $("#tbl_batch").append(temp);

                        if (Excel == "1") {

                            window.location.href = "../Excel_files/" + data.FileName + ".xlsx";

                        }
                    }
                    else {
                        Error_Alert(data.Response);
                    }
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        }

    });

</script>

Code/EXam_Info/Exam_Info/Views/Division/Division_Dashboard.cshtml
@{
    ViewBag.Title = "Division_Dashboard";
    Layout = "~/Views/Shared/Division_LayoutPage.cshtml";
}

<h2 style="text-align:center">Division Dashboard</h2>

<div class="row">
    <table id="divdash"></table>
</div>

<script>

    $(document).ready(function () {
        $.ajax({
            type: 'POST',
            url: '../Admin/Division_Dash_Details',
            dataType: 'json',
            data: {
            },
            beforeSend: function () {
                Showloader();
            },
            complete: function () {
                Hideloader();
            },
            success: function (data) {

                var temp = "";

                if (data.Result) {
                    $("#divdash").empty();
                    $.each(data.Response, function (i, data) {
                        debugger
                        temp += `<tr><td> <h4><a class="blink" style="color:red" href="~/Attachments/` + data.Id + `.jpg">` + (i + 1) + `) ` + data.Heading + `</a></h4></td></tr>`;
                    });
                    temp += `</tbody>`;
                    $("#divdash").append(temp);
                }
                else {
                    Error_Alert(data.Response);
                }
            },
            error: function (ex) {
                alert('Failed.' + ex);
            }
        });
    });
</script>

Code/EXam_Info/Exam_Info/Views/Division/Division_Data_Test3.cshtml
@model IPagedList<Exam_Info.Models.Tbl_DTT3>
@{
    ViewBag.Title = "Division_Data_Test3";
    Layout = "~/Views/Shared/Division_LayoutPage.cshtml";
}
@using PagedList.Mvc;
@using PagedList;





<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    #dist {
        width: 526px;
        padding: 8px;
    }

    #taluka {
        width: 526px;
        padding: 8px;
    }

    #btn_submit {
        width: 200px;
        padding: 5px;
        position: absolute;
        right: 20px;
    }
</style>


<div class="row">
    <div class="col-sm-6">
        <h2>Division Data Test2</h2>
    </div>
    <div class="col-sm-6">
        <input type="button" class="btn btn-success" id="btn_submit" value="Download Excel"><br />
    </div>
</div>

<div class="row" style="border:inset 2px  #3eadcf"></div>
<br />
@using (Html.BeginForm("Division_Data_Test3", "Division", FormMethod.Get))
{
    <div class="table-responsive pt-3  ">
        @Html.Hidden("Div_Code", @TempData["Division_Code"])
        <div class="row">

            <div class="col-sm-4">
                <label for="Division_List">Select District</label><span style="color:Red">*</span>
                <select name="dist" id="dist">
                </select>
            </div>

            <div class="col-sm-4">
                <label for="Taluka_Code">Select Taluka</label><span style="color:Red">*</span>
                <select name="taluka" id="taluka">
                </select>
            </div>
            <div class="col-sm-1">
                <center>
                    <label></label><br />
                    <input type="submit" value="Submit" id="btn_sub" class="btn btn-success" />
                </center>
            </div>
        </div>
        <br />

        <center>
            <table class="AppFormTable " style="background-color: #e7fafe;">
                <tr>
                    <th>
                        Sr. No
                    </th>
                    <th>
                        Index No New
                    </th>
                    <th>
                        Index No Old
                    </th>

                    <th>
                        Date Time
                    </th>
                    <th>
                        MAC
                    </th>
                    <th>
                        Login
                    </th>
                    <th>
                        QP
                    </th>
                    <th>
                        Hit
                    </th>

                </tr>
                @{int i = 1;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <span>@i</span>
                            @{i++;}
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Index_NoN)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Index_No)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Datetime)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.MAC)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Login)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.QP)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Hit)
                        </td>
                    </tr>
                }
            </table>

        </center>
        @Html.PagedListPager(Model, page => Url.Action("Division_Data_Test2", new { page, dist = Request.QueryString["dist"], taluka = Request.QueryString["taluka"] }))
    </div>
}

<script>
    $(document).ready(function () {
        $("#dist").empty();

        $.ajax({
            type: 'POST',
            url: '../Division/Get_District',
            dataType: 'json',
            data: {
                divCode: $("#Div_Code").val()
            },
            success: function (Data) {
                for (var item in Data) {
                    $("#dist").append('<option value="' + Data[item].Value + '">' + Data[item].Text + '</option>');
                }

            },
            error: function (ex) {
                alert('Failed.' + ex);
            }
        });
        $("#dist").change(function () {

            $("#taluka_name").empty();
            $.ajax({
                type: 'POST',
                url: '../District/Get_Taluka',
                dataType: 'json',
                data: {
                    distCode: $("#dist").val()
                },
                success: function (Data) {
                    for (var item in Data) {
                        $("#taluka").append('<option value="' + Data[item].Value + '">' + Data[item].Text + '</option>');
                    }
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
            return false;
        });


        //$("#btn_sub").click(function () {

        //    Get_Inspection_Record("0");

        //});
        $("#btn_submit").click(function () {

            Get_Inspection_Record("1");

        });
        function Get_Inspection_Record(Excel) {
            debugger
            $.ajax({
                type: 'POST',
                url: '../Division/Division_Data_Test3',
                dataType: 'json',
                data: {
                    district: $("#dist").val(),
                    taluka: $("#taluka").val(),
                    Excel: Excel
                },
                beforeSend: function () {
                    Showloader();
                },
                complete: function () {
                    Hideloader();
                },
                success: function (data) {

                    if (data.Result) {
                        //$("#div_insp").empty();

                        //var list2 = JSON.parse(JSON.stringify(data.Response));
                        //for (i in list2) {
                        //    delete list2[i].ID;
                        //    delete list2[i].Active;


                        //    var aa = list2[i].Datetime;
                        //    var JavaScriptDate = new Date(parseInt(aa.substr(6)));
                        //    var dateObject = new Date(JavaScriptDate);
                        //    var daate = dateObject.getDate();
                        //    var Month = dateObject.getMonth() + 1;
                        //    var year = dateObject.getFullYear();
                        //    list2[i].Date_Time = daate + "/" + Month + "/" + year;
                        //}
                        //Bind_Table(list2, "div_insp");
                        if (Excel == "1") {
                            window.location.href = "../State/" + data.FileName + ".xlsx";
                        }
                    }
                    else {
                        Error_Alert(data.Message);
                    }
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        }
    });

</script>