Code/EXam_Info/Exam_Info/Controllers/CollegeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Exam_Info.Helper;
using Exam_Info.Models;
using OfficeOpenXml;



namespace Exam_Info.Controllers
{
    public class CollegeController : Controller
    {
        GKJ_2022Entities db = new GKJ_2022Entities();
        Common common = new Common();
        char[] sep = new char[] { 'ß' };
        char[] back = new char[] { ' ' };
        string[] result2 = new string[20];
        string result;
        // GET: College
        public ActionResult College_DashBoard()
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model mm = common.Get_Board_Details(login_model.Index_No);
            if (login_model == null)
            {
                return RedirectToAction("Login", "Login");
            }

            List<CoOrdinator_Display_Model> CoOr_Display = new List<CoOrdinator_Display_Model>();


            List<Tbl_Division_Co_Ordinator_Registration> tbl1 = db.Database.SqlQuery<Tbl_Division_Co_Ordinator_Registration>("select * from Tbl_Division_Co_Ordinator_Registration where  Active=1  and  substring(Index_No,1,2) in (select district_code from Tbl_Code_Master where division_code ='" + mm.Division_Code + "' )").ToList();
            foreach (Tbl_Division_Co_Ordinator_Registration item in tbl1)
            {
                CoOrdinator_Display_Model m = new CoOrdinator_Display_Model();
                m.Name = item.Coordinator_Name;
                m.Mobile_No = item.Coordinator_Mobile;
                m.Type = "Division Co -Ordinator";
                CoOr_Display.Add(m);
            }
            List<Tbl_State_Co_Ordinator_Registration> tbl = db.Tbl_State_Co_Ordinator_Registration.Where(a => a.Active == 1).ToList();
            foreach (Tbl_State_Co_Ordinator_Registration item in tbl)
            {
                CoOrdinator_Display_Model m = new CoOrdinator_Display_Model();
                m.Name = item.Coordinator_Name;
                m.Mobile_No = item.Coordinator_Mobile;
                m.Type = "State Co -Ordinator";
                CoOr_Display.Add(m);
            }

            var batch = db.Tbl_Batch_Activation.Where(x => x.Active == 1).ToList();
            if (batch != null)
            {
                foreach (var item in batch)
                {
                    if (item.Batch == "B1")
                    {
                        var pass = db.Tbl_Password.Where(x => x.Index_No == login_model.Index_No).Select(n => n.B1).FirstOrDefault();
                        TempData["B1Pass"] = pass;
                    }
                    if (item.Batch == "B2")
                    {
                        var pass = db.Tbl_Password.Where(x => x.Index_No == login_model.Index_No).Select(n => n.B2).FirstOrDefault();
                        //ViewBag.Msg= pass;
                        TempData["B2Pass"] = pass;
                    }
                    if (item.Batch == "B4")
                    {
                        var pass = db.Tbl_Password.Where(x => x.Index_No == login_model.Index_No).Select(n => n.B4).FirstOrDefault();
                        TempData["B4Pass"] = pass;
                    }
                    if (item.Batch == "B3")
                    {
                        var pass = db.Tbl_Password.Where(x => x.Index_No == login_model.Index_No).Select(n => n.B3).FirstOrDefault();
                        TempData["B3Pass"] = pass;
                    }
                    if (item.Batch == "B5")
                    {
                        var pass = db.Tbl_Password.Where(x => x.Index_No == login_model.Index_No).Select(n => n.B5).FirstOrDefault();
                        TempData["B5Pass"] = pass;
                    }
                    if (item.Batch == "B6")
                    {
                        var pass = db.Tbl_Password.Where(x => x.Index_No == login_model.Index_No).Select(n => n.B6).FirstOrDefault();
                        TempData["B6Pass"] = pass;
                    }
                    if (item.Batch == "B7")
                    {
                        var pass = db.Tbl_Password.Where(x => x.Index_No == login_model.Index_No).Select(n => n.B7).FirstOrDefault();
                        TempData["B7Pass"] = pass;
                    }
                }

            }
            College_DashBoard_Model co_model = new College_DashBoard_Model();
            co_model.tbl_College_Registrations = GetCollegeRecord();
            co_model.coOrdinator_Display_Model = CoOr_Display;



            return View(co_model);
        }

        public ActionResult College_Dash_Details()
        {
            var model = db.Admin_tbl.Where(x => x.Type == "College Dashboard" && x.Active == "1").ToList();
            return Json(new { Result = "true", Response = model }, JsonRequestBehavior.AllowGet);

        }
        public List<Tbl_College_Registration> GetCollegeRecord()
        {
            Login_Model login_model = common.Get_Login_Details();
            return db.Tbl_College_Registration.Where(m => m.Index_No == login_model.Index_No).OrderBy(m => m.Index_No).ToList();
        }
        [HttpGet]
        public ActionResult Ans_File_Upload()
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model board_Model = common.Get_Board_Details(login_model.Index_No);
            if (login_model == null)
            {
                return RedirectToAction("Login", "Login");
            }
            if (db.Tbl_File_Upload_Details.Any(x => x.Index_No == login_model.Index_No))
            {
                return Redirect("../Certificate_PDF/" + login_model.Index_No + ".pdf");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Ans_File_Upload(Model2 m)
        {
            string path = Server.MapPath("~/AppFiles/Upload/");
            HttpFileCollectionBase files = Request.Files;
            for (int i = 0; i < files.Count; i++)
            {
                //System.Threading.Thread.Sleep(1000);
                HttpPostedFileBase file = files[i];
                string[] name = file.FileName.Split('/');
                file.SaveAs(path + name[1]);
                ViewBag.Progress = "" + i + "/" + files.Count + " files uploaded.";
                TempData["Prog"] = "" + i + "/" + files.Count + " files uploaded.";
            }
            return Json(files.Count + " Files Uploaded!");
        }

        public ActionResult UploadFile(Model2 m)
        {
            Login_Model login_model = common.Get_Login_Details();
            Board_Model board_Model = common.Get_Board_Details(login_model.Index_No);
            try
            {
                string path = Server.MapPath("~/AppFiles/Upload/");
                HttpFileCollectionBase files = Request.Files;
                for (int i = 0; i < files.Count; i++)
                {
                    //System.Threading.Thread.Sleep(1000);
                    HttpPostedFileBase file = files[i];
                    string[] name = file.FileName.Split('/');
                    file.SaveAs(path + "/" + name[1]);
                    ConvertTotxtFile(Server.MapPath("~/AppFiles/Upload/" + name[1] + ""));
                }
                return Json(new { Result = true, Response = "File Uploaded Successfully" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = false, Response = "Something Went Wrong" + ex }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult UploadNewFile()
        {
            try
            {
                string path = Server.MapPath("~/AppFiles/Upload/");
                HttpFileCollectionBase files = Request.Files;
                for (int i = 0; i < files.Count; i++)
                {
                    //System.Threading.Thread.Sleep(1000);
                    HttpPostedFileBase file = files[i];
                    string[] name = file.FileName.Split('/');
                    file.SaveAs(path + name[0]);
                    ConvertTotxtFile(Server.MapPath("~/AppFiles/Upload/" + name[0] + ""));
                }
                return Json(new { Result = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = false }, JsonRequestBehavior.AllowGet);
            }
        }

        public void ConvertTotxtFile(string path)
        {
            string extension = path.Substring(path.LastIndexOf("."));
            string[] fn = path.Split('\\');
            string fname = fn[fn.Length - 1];

            // if (Path.GetFileName(sFile).StartsWith(letter))
            // {

            string fn1 = fname.Substring(0, fname.LastIndexOf("."));
            if (extension == ".ans")
            {

                string destinationPath = Server.MapPath("~/AppFiles/Ans_File_txt/" + fn1 + ".txt").ToString();
                using (StreamWriter sw = System.IO.File.CreateText(destinationPath))
                {
                    sw.Close();
                }

                TextWriter tw = new StreamWriter(@"" + destinationPath + "");
                // write a line of text to the file
                TextReader re = new StreamReader(path);
                string line = null;
                enc.Class1 ex = new enc.Class1();
                if ((line = re.ReadLine()) != null)
                {
                    string d;
                    // string[] filelines = System.IO.File.ReadAllLines(line);                       
                    //string d = ex.xencryption(line);
                    d = line;
                    tw.WriteLine(d);
                    while ((line = re.ReadLine()) != null)
                    {

Code/EXam_Info/Exam_Info/Views/College/Add_NewStudent.cshtml
@model Exam_Info.Models.Tbl_Login
@{
    ViewBag.Title = "Add_NewStudent";
    Layout = "~/Views/Shared/College_LayoutPage.cshtml";

    

    List<SelectListItem> Hand = new List<SelectListItem>();

    Hand.Add(new SelectListItem { Text = "00", Value = "00" });
    Hand.Add(new SelectListItem { Text = "01", Value = "01", });
    Hand.Add(new SelectListItem { Text = "02", Value = "02" });
    Hand.Add(new SelectListItem { Text = "03", Value = "03", });
    Hand.Add(new SelectListItem { Text = "04", Value = "04" });
    Hand.Add(new SelectListItem { Text = "05", Value = "05", });
    Hand.Add(new SelectListItem { Text = "06", Value = "06" });
    Hand.Add(new SelectListItem { Text = "07", Value = "07", });
    Hand.Add(new SelectListItem { Text = "08", Value = "08" });
    Hand.Add(new SelectListItem { Text = "09", Value = "09", });
    Hand.Add(new SelectListItem { Text = "10", Value = "10" });
    Hand.Add(new SelectListItem { Text = "11", Value = "11", });
    Hand.Add(new SelectListItem { Text = "12", Value = "12" });
    Hand.Add(new SelectListItem { Text = "13", Value = "13", });
    Hand.Add(new SelectListItem { Text = "14", Value = "14" });
    Hand.Add(new SelectListItem { Text = "15", Value = "15" });
    Hand.Add(new SelectListItem { Text = "16", Value = "16", });
    Hand.Add(new SelectListItem { Text = "17", Value = "17" });
    Hand.Add(new SelectListItem { Text = "18", Value = "18", });
    Hand.Add(new SelectListItem { Text = "19", Value = "19" });
    Hand.Add(new SelectListItem { Text = "20", Value = "20", });
    Hand.Add(new SelectListItem { Text = "21", Value = "21" });
    Hand.Add(new SelectListItem { Text = "22", Value = "22", });
    Hand.Add(new SelectListItem { Text = "23", Value = "23" });
    Hand.Add(new SelectListItem { Text = "24", Value = "24", });
    Hand.Add(new SelectListItem { Text = "25", Value = "25" });
    Hand.Add(new SelectListItem { Text = "26", Value = "26", });
    Hand.Add(new SelectListItem { Text = "27", Value = "27" });
    Hand.Add(new SelectListItem { Text = "28", Value = "28", });
    Hand.Add(new SelectListItem { Text = "29", Value = "29" });
    Hand.Add(new SelectListItem { Text = "30", Value = "30" });
    Hand.Add(new SelectListItem { Text = "31", Value = "31", });
    Hand.Add(new SelectListItem { Text = "32", Value = "32" });
    Hand.Add(new SelectListItem { Text = "33", Value = "33", });
    Hand.Add(new SelectListItem { Text = "34", Value = "34" });
    Hand.Add(new SelectListItem { Text = "35", Value = "35", });
    Hand.Add(new SelectListItem { Text = "36", Value = "36" });
    Hand.Add(new SelectListItem { Text = "37", Value = "37" });
    Hand.Add(new SelectListItem { Text = "38", Value = "38", });
    Hand.Add(new SelectListItem { Text = "39", Value = "39" });
    Hand.Add(new SelectListItem { Text = "40", Value = "40", });
    Hand.Add(new SelectListItem { Text = "41", Value = "41" });
    Hand.Add(new SelectListItem { Text = "42", Value = "42", });
    Hand.Add(new SelectListItem { Text = "43", Value = "43" });
    Hand.Add(new SelectListItem { Text = "44", Value = "44", });
    Hand.Add(new SelectListItem { Text = "45", Value = "45" });
    Hand.Add(new SelectListItem { Text = "46", Value = "46", });
    Hand.Add(new SelectListItem { Text = "47", Value = "47" });
    Hand.Add(new SelectListItem { Text = "48", Value = "48", });
    Hand.Add(new SelectListItem { Text = "49", Value = "49" });
    Hand.Add(new SelectListItem { Text = "50", Value = "50", });
}




  
    
   
}



<style>
    select #Hand {
        width: 60px;
        height: 30px;
        text-align: center;
    }
</style>
<div class="row">
    <div class="col-sm-6">
        <h2>Add_Student </h2>
    </div>

</div>

<div class="row" style="border:inset 2px  #3eadcf"></div>
<br />

@using (Html.BeginForm("Add_NewStudent", "College", FormMethod.Post))
{


    <div class="table-responsive pt-3  ">
        <div class="row">

            <div class="col-sm-2">


                @Html.LabelFor(model => model.Seat_No, "Seat_No", htmlAttributes: new { @class = "control-label " })
                @Html.EditorFor(model => model.Seat_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seat_No, "", new { @class = "text-danger" })

            </div>
            <div class="col-sm-2">
                <div class="col-sm-2">
                    @Html.LabelFor(model => model.Stream, "Stream", htmlAttributes: new { @class = "control-label " })
                    @Html.TextBox("Stream", TempData["Stream"])
                </div>

            </div>
            @*<label for="Stream">Select Stream</label><span style="color:Red">*</span>
        <select name="Stream" id="Stream">
            <option value="0">--Select Stream--</option>
            <option value="Science">Science</option>
            <option value="Commerce">Commerce</option>
            <option value="Arts">Arts</option>
        </select>*@
            <div class="col-sm-2">
                @Html.LabelFor(model => model.Mother_Name, "Mother_Name", htmlAttributes: new { @class = "control-label " })
                <span class="required" style="color:red;font-weight:bold">*</span>
                @Html.EditorFor(model => model.Mother_Name, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Mother_Name, "", new { @class = "text-danger" })

            </div>

            <div class="col-sm-2">
                @Html.LabelFor(model => model.Name, "Name", htmlAttributes: new { @class = "control-label " })
                <span class="required" style="color:red;font-weight:bold">*</span>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-2">
                <label for="Hand">Select Handicap Type</label>

                <span style="color:Red">*</span>

                @Html.DropDownListFor(model => model.Hand, Hand, "--Select Handicape Type--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Hand, "", new { @class = "text-danger" })

            </div>

        </div>


        <div class="col-sm-2">
            <label></label><br />
            <input type="submit" value="Submit" id="btn_sub" class="btn btn-success" />
        </div>
    </div>

}

Code/EXam_Info/Exam_Info/Views/College/Add_Student.cshtml
@model Exam_Info.Models.Tbl_Login
@{
    ViewBag.Title = "Add_Student";
    Layout = "~/Views/Shared/State_LayoutPage.cshtml";

    List<SelectListItem> Stream = new List<SelectListItem>();
    Stream.Add(new SelectListItem { Text = "Science", Value = "97" });
    Stream.Add(new SelectListItem { Text = "Commerce", Value = "98", });
    Stream.Add(new SelectListItem { Text = "Arts", Value = "99" });

    List<SelectListItem> Hand = new List<SelectListItem>();

    Hand.Add(new SelectListItem { Text = "00", Value = "00" });
    Hand.Add(new SelectListItem { Text = "01", Value = "01", });
    Hand.Add(new SelectListItem { Text = "02", Value = "02" });
    Hand.Add(new SelectListItem { Text = "03", Value = "03", });
    Hand.Add(new SelectListItem { Text = "04", Value = "04" });
    Hand.Add(new SelectListItem { Text = "05", Value = "05", });
    Hand.Add(new SelectListItem { Text = "06", Value = "06" });
    Hand.Add(new SelectListItem { Text = "07", Value = "07", });
    Hand.Add(new SelectListItem { Text = "08", Value = "08" });
    Hand.Add(new SelectListItem { Text = "09", Value = "09", });
    Hand.Add(new SelectListItem { Text = "10", Value = "10" });
    Hand.Add(new SelectListItem { Text = "11", Value = "11", });
    Hand.Add(new SelectListItem { Text = "12", Value = "12" });
    Hand.Add(new SelectListItem { Text = "13", Value = "13", });
    Hand.Add(new SelectListItem { Text = "14", Value = "14" });
    Hand.Add(new SelectListItem { Text = "15", Value = "15" });
    Hand.Add(new SelectListItem { Text = "16", Value = "16", });
    Hand.Add(new SelectListItem { Text = "17", Value = "17" });
    Hand.Add(new SelectListItem { Text = "18", Value = "18", });
    Hand.Add(new SelectListItem { Text = "19", Value = "19" });
    Hand.Add(new SelectListItem { Text = "20", Value = "20", });
    Hand.Add(new SelectListItem { Text = "21", Value = "21" });
    Hand.Add(new SelectListItem { Text = "22", Value = "22", });
    Hand.Add(new SelectListItem { Text = "23", Value = "23" });
    Hand.Add(new SelectListItem { Text = "24", Value = "24", });
    Hand.Add(new SelectListItem { Text = "25", Value = "25" });
    Hand.Add(new SelectListItem { Text = "26", Value = "26", });
    Hand.Add(new SelectListItem { Text = "27", Value = "27" });
    Hand.Add(new SelectListItem { Text = "28", Value = "28", });
    Hand.Add(new SelectListItem { Text = "29", Value = "29" });
    Hand.Add(new SelectListItem { Text = "30", Value = "30" });
    Hand.Add(new SelectListItem { Text = "31", Value = "31", });
    Hand.Add(new SelectListItem { Text = "32", Value = "32" });
    Hand.Add(new SelectListItem { Text = "33", Value = "33", });
    Hand.Add(new SelectListItem { Text = "34", Value = "34" });
    Hand.Add(new SelectListItem { Text = "35", Value = "35", });
    Hand.Add(new SelectListItem { Text = "36", Value = "36" });
    Hand.Add(new SelectListItem { Text = "37", Value = "37" });
    Hand.Add(new SelectListItem { Text = "38", Value = "38", });
    Hand.Add(new SelectListItem { Text = "39", Value = "39" });
    Hand.Add(new SelectListItem { Text = "40", Value = "40", });
    Hand.Add(new SelectListItem { Text = "41", Value = "41" });
    Hand.Add(new SelectListItem { Text = "42", Value = "42", });
    Hand.Add(new SelectListItem { Text = "43", Value = "43" });
    Hand.Add(new SelectListItem { Text = "44", Value = "44", });
    Hand.Add(new SelectListItem { Text = "45", Value = "45" });
    Hand.Add(new SelectListItem { Text = "46", Value = "46", });
    Hand.Add(new SelectListItem { Text = "47", Value = "47" });
    Hand.Add(new SelectListItem { Text = "48", Value = "48", });
    Hand.Add(new SelectListItem { Text = "49", Value = "49" });
    Hand.Add(new SelectListItem { Text = "50", Value = "50", });

}



<style>
    select #Hand {
        width: 60px;
        height: 30px;
        text-align: center;
    }
    
    </style>
<div class="row">
    <div class="col-sm-6">
        <h2>Add_Student </h2>
    </div>

</div>

<div class="row" style="border:inset 2px  #3eadcf"></div>
<br />

@using (Html.BeginForm("Add_Student", "College", FormMethod.Post))
{


    <div class="table-responsive pt-3  ">
        <div class="row">

            <div class="col-sm-2">
            

                @Html.LabelFor(model => model.Seat_No, "Seat_No", htmlAttributes: new { @class = "control-label " })
                @Html.EditorFor(model => model.Seat_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seat_No, "", new { @class = "text-danger" })

            </div>

            <div class="col-sm-2">
                <label for="Stream">Select Stream</label><span style="color:Red">*</span>

                @Html.DropDownListFor(model => model.Stream, Stream, "--Select Stream--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Stream, "", new { @class = "text-danger" })

            </div>

            <div class="col-sm-2">
                @Html.LabelFor(model => model.Mother_Name, "Mother_Name", htmlAttributes: new { @class = "control-label " })
                <span class="required" style="color:red;font-weight:bold">*</span>
                @Html.EditorFor(model => model.Mother_Name, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Mother_Name, "", new { @class = "text-danger" })

            </div>

            <div class="col-sm-2">
                @Html.LabelFor(model => model.Name, "Name", htmlAttributes: new { @class = "control-label " })
                <span class="required" style="color:red;font-weight:bold">*</span>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-2">
                <label for="Hand">Select Handicap Type</label>

                <span style="color:Red">*</span>

                @Html.DropDownListFor(model => model.Hand, Hand, "--Select Handicape Type--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Hand, "", new { @class = "text-danger" })

            </div>

        </div>


        <div class="col-sm-2">
            <label></label><br />
            <input type="submit" value="Submit" id="btn_sub" class="btn btn-success" />
        </div>
    </div>

}

Code/EXam_Info/Exam_Info/Views/College/College_Inspection.cshtml
@model IEnumerable<Exam_Info.Models.Tbl_Inspection>
@{
    ViewBag.Title = "College_Inspection";
    Layout = "~/Views/Shared/College_LayoutPage.cshtml";
}



<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    #btn_submit {
        width: 200px;
        padding: 5px;
        position: absolute;
        right: 20px;
    }
</style>

<div class="row">
    <div class="col-sm-6">
        <h2>College Inspection</h2>
        </div>
    <div class="col-sm-6">
        @*<input type="button" class="btn btn-success" id="btn_submit" value="Download Excel" onclick="return confirm('Do you want to download ?')"><br />*@
        <button class="btn btn-success" id="btn_submit" onclick="return confirm('Do you want to download ?')">@Html.ActionLink("Download Excel", "ExportToExcelV", "College", new { controller = "College" })</button><br />
        @*<button style="padding:10px;margin-top:5px;margin-bottom:5px;">@Html.ActionLink("DOWNLOAD", "ExportToExcelV", "College", new { controller = "College" })</button>*@
    </div>
</div>

    <div class="row" style="border:inset 2px  #3eadcf"></div>

    <br />

    <div class="table-responsive pt-3  ">
        <center>
            <table class="AppFormTable " style="background-color: #e7fafe;">
                <tr>
                    
                    <th>
                        Index No
                    </th>
                    <th>
                        System No
                    </th>
                    <th>
                        OS Name
                    </th>
                    <th>
                        RAM
                    </th>
                    <th>
                        HDD
                    </th>
                    <th>
                        MAC
                    </th>
                    <th>
                        Browser Name
                    </th>
                    <th>
                        External IP
                    </th>
                    <th>
                        Screen Res
                    </th>
                    <th>
                        IE Version
                    </th>
                    <th>
                        Active
                    </th>

                </tr>
              
                @foreach (var item in Model)
                {
                    <tr>
                        
                        <td>
                            @Html.DisplayFor(model => item.Index_No)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.SYS_No)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.OS_Name)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Ram)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.HDD)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.MAC)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Browser_Name)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Extn_IP)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Screen_Res)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.IE_Version)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Active)
                        </td>
                    </tr>
                }
            </table>
        </center>
    </div>

Code/EXam_Info/Exam_Info/Views/College/Data_Test3.cshtml
@model IEnumerable<Exam_Info.Models.Tbl_DTT3>
@{
    ViewBag.Title = "Data_Test3";
    Layout = "~/Views/Shared/College_LayoutPage.cshtml";
}

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    #btn_submit {
        width: 200px;
        padding: 5px;
        position: absolute;
        right: 20px;
    }
</style>

<div class="row">
    <div class="col-sm-6">
        <h2>Data Test3</h2>
    </div>
    <div class="col-sm-6">
        <button class="btn btn-success" id="btn_submit" onclick="return confirm('Do you want to download ?')">@Html.ActionLink("Download Excel", "College_DTT3", "College", new { controller = "College" })</button><br />
    </div>
</div>


<div class="row" style="border:inset 2px  #3eadcf"></div>
<br />

<div class="table-responsive pt-3  ">
    <center>
        <table class="AppFormTable " style="background-color: #e7fafe;">
            <tr>
                <th>
                    Sr. No
                </th>
                <th>
                    Index No New
                </th>
                <th>
                    Index No Old
                </th>

                <th>
                    Date Time
                </th>
                <th>
                    MAC
                </th>
                <th>
                    Login
                </th>
                <th>
                    QP
                </th>
                <th>
                    Hit
                </th>

            </tr>
            @{int i = 1;}
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <span>@i</span>
                        @{i++;}
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Index_NoN)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Index_No)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Datetime)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.MAC)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Login)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.QP)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Hit)
                    </td>
                </tr>
            }
        </table>
    </center>
</div>

Code/EXam_Info/Exam_Info/Views/College/ProgressView.cshtml
<div>

    <label id="prog">@TempData["Prog"]</label>


</div>